# SPDX-License-Identifier: Apache-2.0

version: "2"
linters:
  enable:
    - bodyclose
    - goconst
    - gocyclo
    - gosec
    - misspell
    - noctx
    - revive
    - unconvert
    - unparam
  settings:
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G101
        - G104
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: stutters
    paths:
      - vendor
      - examples
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
